variables:
  IMAGE_REF: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_PIPELINE_ID
  MAVEN_CLI_OPTS: -s /.m2/settings.xml --batch-mode
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

stages:
  - maven-build
  - docker-build
  - git-argocd

maven-build:
  stage: maven-build
  image: maven:3.6.3-adoptopenjdk-11
  script:
    - mvn -U $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/app.jar
    expire_in: 3m
  cache:
    paths:
      - .m2

docker-build:
  stage: docker-build
  image: docker:git
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.baixing.cn
    - docker build -t $IMAGE_REF .
    - docker push $IMAGE_REF
    - docker rmi $IMAGE_REF

git-argocd:
  stage: git-argocd
  image: smartive/kustomize:kustomize-v3.8.1_kubectl-v1.18.6
  only:
    - master@devcloud/devcloud-app
  before_script:
    - git remote set-url origin https://bxbot:$CI_PASSWORDCAye@gitlab.baixing.cn/devcloud/devcloud-iaas.git
    - git config --global user.name "bxbot"
    - git config --global user.email "arch@baixing.com"
  script:
    - git clone https://bxbot:$CI_PASSWORD@gitlab.baixing.cn/devcloud/devcloud-iaas.git /opt/devcloud-iaas
    - cd /opt/devcloud-iaas
    - git pull
    - cd /opt/devcloud-iaas/devcloud/devcloud-app
    - kustomize edit set image $IMAGE_REF
    - git commit -am 'image update'
    - git push origin master
